docs:
  - all:
    - changed-files:
      - any-glob-to-any-file:
        - docs/en/docs/**
        - docs_src/**
      - all-globs-to-all-files:
        - '!readyapi/**'
        - '!pyproject.toml'
        - '!docs/en/data/sponsors.yml'
        - '!docs/en/overrides/main.html'

lang-all:
  - all:
    - changed-files:
      - any-glob-to-any-file:
        - docs/*/docs/**
      - all-globs-to-all-files:
        - '!docs/en/docs/**'
        - '!readyapi/**'
        - '!pyproject.toml'

internal:
  - all:
    - changed-files:
      - any-glob-to-any-file:
        - .github/**
        - scripts/**
        - .gitignore
        - .pre-commit-config.yaml
        - pdm_build.py
        - requirements*.txt
        - docs/en/data/sponsors.yml
        - docs/en/overrides/main.html
      - all-globs-to-all-files:
        - '!docs/*/docs/**'
        - '!readyapi/**'
        - '!pyproject.toml'
