name: Latest Changes

on:
  pull_request_target:
    branches:
      - master
    types:
      - closed
  workflow_dispatch:
    inputs:
      number:
        description: PR number
        required: true
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: 'false'

jobs:
  latest-changes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4.1.2
        with:
          # To allow latest-changes to commit to master
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker://ghcr.io/khulnasoft/latest-changes:0.3.0
      # - uses: khulnasoft/latest-changes@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
